# Configuration
language: node_js
node_js: [
	node,
]

# The pre-install script
before_install: [
	npm i -g pnpm,
]

# The install script
install: [
	pnpm install,
]

# The build script
script: [
	pnpm run lint,
]

# Disable email notifications
notifications: {
	email: false
}
